services:
  api:
    build: ./api
    image: humnafatima/api
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=student_user
      - POSTGRES_PASSWORD=student_password
      - POSTGRES_DATABASE=labo
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - PORT=8080

  frontend:
    build: ./web
    image: humnafatima/frontend
    expose:
      - 8000
    environment:
      - FLASK_SECRET_KEY=my_super_secret_custom_key_1
      - JWT_SECRET_KEY=SG9wZW54pamsgZ2VicnVpaHN0dWRlbnQgZG10IG9vaXQgbnV0dG1nZz09

  nginx:
    build: ./nginx
    image: humnafatima/nginx
    ports:
      - 80:80

  postgres:
    image: 'docker.io/postgres:18.2-alpine'
    environment:
      - POSTGRES_USER=student_user
      - POSTGRES_PASSWORD=student_password
      - POSTGRES_DB=labo
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:


